apiVersion: v1
kind: Service
metadata:
  name: overseerr-service
  namespace: media-center
spec:
  selector:
    app: overseerr
  type: ClusterIP
  ports:
    - name: http
      port: 5055
      targetPort: 5055
  externalIPs:
    - 192.168.1.134
