apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: media-center
spec:
  selector:
    app: sonarr
  type: ClusterIP
  ports:
    - name: http
      port: 8989
      targetPort: 8989
  externalIPs:
    - 192.168.1.134
