apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/k3s_pv
