apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 80
        - containerPort: 53
        env:
        - name: TZ
          value: Europe/Madrid
        - name: WEBPASSWORD
          value: ''
        volumeMounts:
          - name: pihole-data
            mountPath: /etc/pihole
            subPath: pihole/config
          - name: pihole-data
            mountPath: /etc/dnsmasq.d
            subPath: pihole/dnsmasq.d
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-pvc
