apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
spec:
  selector:
    app: pihole
  type: ClusterIP
  #type: LoadBalancer
  ports:
    - name: web
      port: 8080
      targetPort: 80
    - name: dns-upd
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  externalIPs:
    - 192.168.1.134
  externalTrafficPolicy: Local
