apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/k3s_pv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-ha-pv
spec:
  storageClassName: manual
  capacity:
    storage: 140Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/media