apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:latest
        ports:
        - containerPort: 8123
        env:
        - name: TZ
          value: Europe/Madrid
        volumeMounts:
          - name: home-assistant-data
            mountPath: /config
            subPath: home-assistant/config
          - name: media-data
            mountPath: /media
            subPath: pelis
      volumes:
        - name: home-assistant-data
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name: media-data
          persistentVolumeClaim:
            claimName: media-ha-pvc
