apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  namespace: home-assistant
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
  externalIPs:
    - 192.168.1.134
