apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - name: bazarr
        image: linuxserver/bazarr:latest
        ports:
        - containerPort: 6767
        env:
        - name: TZ
          value: Europe/Madrid
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
          - name: bazarr-data
            mountPath: /config
            subPath: bazarr/config
          - name: bazarr-data
            mountPath: /movies
            subPath: media/pelis
          - name: bazarr-data
            mountPath: /tv
            subPath: media/series
      volumes:
        - name: bazarr-data
          persistentVolumeClaim:
            claimName: media-center-pvc
