apiVersion: v1
kind: Service
metadata:
  name: bazarr-service
  namespace: media-center
spec:
  selector:
    app: bazarr
  type: ClusterIP
  ports:
    - name: http
      port: 6767
      targetPort: 6767
  externalIPs:
    - 192.168.1.134