apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
  namespace: cert-manager
spec:
  secretName: my-certificate-secret
  commonName: uriart.sytes.net
  dnsNames:
  - uriart.sytes.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
