apiVersion: v1
kind: Service
metadata:
  name: plex-media-server-service
  namespace: media-center
spec:
  selector:
    app: plex-media-server
  type: ClusterIP
  ports:
    - name: http
      port: 3240
      targetPort: 32400
  externalIPs:
    - 192.168.1.134
