services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: bridge
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "Europe/Madrid"
      DNSMASQ_LISTENING: "all"
    volumes:
      - ./pihole_config/etc-pihole:/etc/pihole
      - ./pihole_config/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    env_file:
      - .env