apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  namespace: media-center
spec:
  selector:
    app: transmission
  type: ClusterIP
  ports:
    - name: first
      port: 9091
      targetPort: 9091
    - name: second
      port: 51413
      targetPort: 51413
    - name: third
      protocol: UDP
      port: 51413
      targetPort: 51413
  externalIPs:
    - 192.168.1.134
