apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:latest
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
          - name: mosquitto-conf
            mountPath: /mosquitto
            subPath: mosquitto
          - name: mosquitto-config
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
      volumes:
        - name: mosquitto-conf
          persistentVolumeClaim:
            claimName: mosquitto-pvc
        - name: mosquitto-config
          configMap:
            name: mosquitto-configmap
            items:
            - key: mosquitto.conf
              path: mosquitto.conf
