apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: mosquitto
spec:
  selector:
    app: mosquitto
  type: ClusterIP
  ports:
    - name: port1
      port: 1883
      targetPort: 1883
    - name: port2
      port: 9001
      targetPort: 9001
  externalIPs:
    - 192.168.1.134
