apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: media-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        ports:
        - containerPort: 9117
        env:
        - name: TZ
          value: Europe/Madrid
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
          - name: jackett-data
            mountPath: /downloads
            subPath: transmission/downloads
          - name: jackett-data
            mountPath: /config
            subPath: jackett/config
      volumes:
        - name: jackett-data
          persistentVolumeClaim:
            claimName: media-center-pvc
