apiVersion: v1
kind: Service
metadata:
  name: jackett-service
  namespace: media-center
spec:
  selector:
    app: jackett
  type: ClusterIP
  ports:
    - name: http
      port: 9117
      targetPort: 9117
  externalIPs:
    - 192.168.1.134
