apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: media-center
spec:
  selector:
    app: radarr
  type: ClusterIP
  ports:
    - name: http
      port: 7878
      targetPort: 7878
  externalIPs:
    - 192.168.1.134
